### ISSUE TITLE
What's the difference between RTM and RTC tokens?

### ISSUE THREAD

**Issue by noway** [AgoraIO/Tools#52]
The distinction is shown here: https://github.com/AgoraIO/Tools/tree/master/DynamicKey/AgoraDynamicKey/nodejs/sample but it's not explained. Which one should I use for say `RtcEngine.joinChannelWithUserAccount`?

**Comment by plutoless** [comment]
They are two different products.
RTM aka Real Time Messaging is a SDK for you to send instant signaling messages. https://docs.agora.io/en/Real-time-Messaging/product_rtm?platform=All%20Platforms
RTC is a SDK for you to do real time video/audio communication.
https://docs.agora.io/en/Interactive%20Broadcast/product_live?platform=All%20Platforms

Since you are using RTC SDK so you should use RTC tokens.

**Comment by shreyas-jadhav** [comment]
If i'm using both RTC and RTM together, given that each user have same UID and Channel Name, so can I use the same token which I generated for RTC and apply it to RTM sdk too? Or do I have to generate seperate tokens for each of the SDK?

**Comment by plutoless** [comment]
no you can't you have to generate two tokens.

**Comment by scheung38** [comment]
Hi @plutoless on the subject of RTM, what protocol is Signaling using? TCP, UDP or normal HTTPS? As I got difference information depending on where I read. Thanks

**Comment by waqarilyas** [comment]
what type of token should I use if I am implementing only text chat?
